"""empty message

Revision ID: 092d0dba69f1
Revises: 976f4eb8e7d0
Create Date: 2022-04-11 10:06:48.362113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092d0dba69f1'
down_revision = '976f4eb8e7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_title', table_name='post')
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.drop_index('ix_user_email', table_name='user_account')
    op.drop_index('ix_user_username', table_name='user_account')
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.create_index('ix_user_username', 'user_account', ['username'], unique=False)
    op.create_index('ix_user_email', 'user_account', ['email'], unique=False)
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    # ### end Alembic commands ###
