"""followers

Revision ID: 976f4eb8e7d0
Revises: e0c5d946b019
Create Date: 2022-04-07 12:30:22.887400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976f4eb8e7d0'
down_revision = 'e0c5d946b019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
