"""new fields in user model

Revision ID: e0c5d946b019
Revises: 06ddd5ce9336
Create Date: 2022-04-06 10:48:59.977438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c5d946b019'
down_revision = '06ddd5ce9336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user_account', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'last_seen')
    op.drop_column('user_account', 'about_me')
    # ### end Alembic commands ###
